name: README Health Check

on:
  schedule:
    - cron: '0 9 * * 5' # Every Friday at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run README health check
        run: python scripts/readme_health_check.py

      - name: Upload health report
        uses: actions/upload-artifact@v4
        with:
          name: readme-health-report
          path: readme_health_report.md
          retention-days: 30

      - name: Create issue on broken links
        if: always()
        run: |
          if [ -f readme_health_report.md ]; then
            if grep -q "❌ Broken URLs" readme_health_report.md; then
              echo "Broken links detected. Consider creating an issue."
              # You can add GitHub CLI commands here to create issues automatically
            fi
          fi