name: Rotate README Quote

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes   
  workflow_dispatch:     

permissions:
  contents: write

jobs:
  rotate-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update README quote
        run: python scripts/update_quote.py

      - name: Pull latest changes
        run: |
          git fetch origin
          # Stash any unstaged changes before rebase
          if ! git diff --quiet || ! git diff --cached --quiet; then
            git stash push -m "temporary stash before rebase"
            STASHED=true
          else
            STASHED=false
          fi
          git rebase origin/master
          # Restore stashed changes if any
          if [ "$STASHED" = "true" ]; then
            git stash pop
          fi

      - name: Commit & push (if changed)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): rotate quote"
            git push
          else
            echo "No changes to commit."
          fi